.PHONY: clean All

All:
	@echo "----------Building project:[ ml1 - Debug ]----------"
	@cd "ml1" && "$(MAKE)" -f  "ml1.mk"
clean:
	@echo "----------Cleaning project:[ ml1 - Debug ]----------"
	@cd "ml1" && "$(MAKE)" -f  "ml1.mk" clean
